application: chartit-demo-app
version: 1
runtime: python27
api_version: 1
threadsafe: yes

# Uncomment before releasing to production
# default_expiration: "30d"

handlers:
- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: favicon\.ico

- url: /css
  static_dir: static/css

- url: /js
  static_dir: static/js

- url: /img
  static_dir: static/img

- url: /.*
  script: application.app

